### ISSUE TITLE
Use of being declared variable inside its own initializer

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/asteria#85]
# Synopsis

In languages that distinguish _definitions_ from _assignments_ and have variables with _scopes_, what would you expect the following pseudo code to output?

```text
DEFINE a AS INTEGER = 1
IF true THEN
  DEFINE a AS INTEGER = a + 1    # should name lookup find the first or second `a`?
  PRINT "inner a = ", a
END IF
PRINT "outer a = ", a
```

# Examples

## Node.js

```javascript
let a = 1;
if(true) {
  let a = a + 1;
  console.log("inner: a = ", a);
}
console.log("outer: a = ", a);

```
gives
```text
/dev/pts/0:3
  let a = a + 1;
          ^

ReferenceError: a is not defined
    at Object.<anonymous> (/dev/pts/0:3:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

## Lua

```lua
local a = 1
if true then
  local a = a + 1
  print("inner: a = ", a)
end
print("outer: a = ", a)
```
gives
```text
inner: a =      2
outer: a =      1
```

## Perl

```perl
my $a = 1;
if(true) {
  my $a = $a + 1;
  print("inner: $$a = $a\n");
}
print("outer: $$a = $a\n");
```
gives
```
inner:  = 2
outer:  = 1
```

**Comment by lhmouse** [comment]
I think that **JavaScript** is right. Inside the initializer of a variable, it should be considered to have been declared and visible. It is just the `ReferenceError: a is not defined` message that is vague and cryptic. This principle also holds in **C** and **C++** although copying an uninitialized variable results in _undefined behavior_. 

ATM in **Asteria**, in such a case the variable is considered as if it was declared as `const VAR = null` but I personally prefer the **Node.js** solution; it should be invalid to read from or write to such variables until its initialization is complete.

Note that this does not forbid referencing the variable (not reading or writing):
```go
var a = func() { return typeof a;  };   // `a` is a function returning its own type, which is not invalid.
```

**Comment by lhmouse** [comment]
Fixed so far. Now we get this in the REPL:

```text
#2:1> var a = func(){ return a;  };  std.debug.print("a = $1", a);
2020-01-05 22:21:38.856 @@ asteria/src/library/bindings_debug.cpp:27
        a = <function> [[`<closure>._1() @ snippet #2:1`]]
* result #2: <void>
```
